### ISSUE TITLE
[ BUG ] : testconatiner 여러번 초기화 문제

### ISSUE THREAD

**Issue by hodu31** [4monument/sb1-monew-team04#101]
# ✨ motivation

현재 계속 application-test.yaml 파일에서 schema-test.sql 이 testcontainers를 쓰는 테스트 마다 실행하는 과정에서 
병렬로 테스트가 진해되기 때문에 DB를 사용중에 초기화 해버림 
```
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-test.sql
```

# 해결

### flyway 의존성을 추가해서 DB 관리 시키게 하기

build.gradle 에 아래코드 추가
```
implementation "org.flywaydb:flyway-core:10.10.0"
implementation "org.flywaydb:flyway-database-postgresql"
```

### schema.sql을 이름변경해서 아래에 위치시키기

![Image](https://github.com/user-attachments/assets/830748b6-efa6-4dad-91d9-4a0eaf686007)

### 이렇게 하면 DB에 스키마 적용을 한번만 하면서 싱글톤 패턴으로 testcontainers를 관리 할 수 있습니다.

# 📝 modification

- []
* 수정할 내용 (TODO): 정확하게 어떤 걸 수정할 것인지*

# 💬 etc
* 기타 사항 *git
