### ISSUE TITLE
[ BUG ] : 스키마가 같은데 validate하면 오류나는부분

### ISSUE THREAD

**Issue by hodu31** [4monument/sb1-monew-team04#152]
# ✨ motivation
```
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
```

 - validate로 하면 articles가 없다고하고
 - none으로 해도 DB에 문제 있다고 함

# 📝 modification

- []
* 수정할 내용 (TODO): 정확하게 어떤 걸 수정할 것인지*

# 💬 etc
* 기타 사항 *git
